logging:
  level:
    # 该属性在“生产环境”需要设置为“warn”
    root: info
  # 日志的存放路径
  path: logs
  file:
    max-history: 90

server:
  # Server HTTP port.
  port: 8888

 # redis相关配置
redis:
  host: 39.108.131.51
  port: 6379
  password: