logging:
  level:
    # 该属性在“生产环境”需要设置为“warn”
    root: info
  # 日志的存放路径
  path: logs
  file:
    max-history: 90

server:
  # Server HTTP port.
  port: 8888

 # redis相关配置
redis:
  host: 39.108.131.51
  port: 6379
  password:

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://39.108.131.51:3456/forewei_seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # 消息队列配置
  rabbitmq:
    host: 39.108.131.51
    port: 5672
    username: user
    password: user
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
    listener:
      simple:
        prefetch: 1
        concurrency: 10
        max-concurrency: 10
        auto-startup: true
        default-requeue-rejected: true
